// Generated by Scripts/svg2swift.swift from paint-and-transforms.svg - do not edit by hand.
//
// Regenerate with:
//     swift Scripts/svg2swift.swift <path>/paint-and-transforms.svg PaintFixtureArt \
//         > Sources/UI/Art/PaintFixtureArt.swift

import SwiftUI

/// Drawn from `paint-and-transforms.svg`, authored in a 100 x 100 frame.
///
/// Scales to whatever size it is given: every coordinate goes through `p()`, which maps
/// the design frame onto the view's bounds, so the art has no fixed size of its own.
struct PaintFixtureArt: View {
    var body: some View {
        Canvas { context, size in
            let rect = CGRect(origin: .zero, size: size)

            /// A design-space point mapped into the view's bounds.
            func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
                CGPoint(x: rect.minX + (x - 10) / 100 * rect.width,
                        y: rect.minY + (y - 20) / 100 * rect.height)
            }
            /// Stroke widths key off width alone, matching the rest of `Sources/UI/Art` -
            /// scaling them off the smaller axis thins every line on a non-square frame.
            func w(_ v: CGFloat) -> CGFloat { v / 100 * rect.width }
            func shape(_ build: (inout Path) -> Void) -> Path { var p = Path(); build(&p); return p }

            // 1. rect
            let shape0 = shape {
                $0.move(to: p(10, 20))
                $0.addLine(to: p(30, 20))
                $0.addLine(to: p(30, 30))
                $0.addLine(to: p(10, 30))
                $0.closeSubpath()
            }
            context.fill(shape0, with: .color(Color(hex: "#FF0000")))

            // 2. rect
            let shape1 = shape {
                $0.move(to: p(35, 20))
                $0.addLine(to: p(55, 20))
                $0.addLine(to: p(55, 30))
                $0.addLine(to: p(35, 30))
                $0.closeSubpath()
            }
            context.fill(shape1, with: .color(Color(hex: "#0080FF")))

            // 3. rect
            let shape2 = shape {
                $0.move(to: p(60, 20))
                $0.addLine(to: p(80, 20))
                $0.addLine(to: p(80, 30))
                $0.addLine(to: p(60, 30))
                $0.closeSubpath()
            }
            context.fill(shape2, with: .color(Color(hex: "#00FF00")))

            // 4. rect
            let shape3 = shape {
                $0.move(to: p(85, 20))
                $0.addLine(to: p(105, 20))
                $0.addLine(to: p(105, 30))
                $0.addLine(to: p(85, 30))
                $0.closeSubpath()
            }
            context.fill(shape3, with: .color(Color(hex: "#000000")))

            // 5. rect
            let shape4 = shape {
                $0.move(to: p(24.559, 40))
                $0.addLine(to: p(42.559, 40))
                $0.addLine(to: p(46.199, 50))
                $0.addLine(to: p(28.199, 50))
                $0.closeSubpath()
            }
            context.fill(shape4, with: .color(Color(hex: "#008080")))

            // 6. rect
            let shape5 = shape {
                $0.move(to: p(40, 50.718))
                $0.addLine(to: p(58, 55.541))
                $0.addLine(to: p(58, 65.541))
                $0.addLine(to: p(40, 60.718))
                $0.closeSubpath()
            }
            context.fill(shape5, with: .color(Color(hex: "#000080")))

            // 7. rect
            let shape6 = shape {
                $0.move(to: p(70, 50))
                $0.addLine(to: p(97, 50))
                $0.addLine(to: p(97, 55))
                $0.addLine(to: p(70, 55))
                $0.closeSubpath()
            }
            context.fill(shape6, with: .color(Color(hex: "#808000")))

            // 8. path
            let shape7 = shape {
                $0.move(to: p(30, 85))
                $0.move(to: p(12, 85))
                $0.addCurve(to: p(30, 103), control1: p(12, 94.941), control2: p(20.059, 103))
                $0.addCurve(to: p(48, 85), control1: p(39.941, 103), control2: p(48, 94.941))
                $0.addCurve(to: p(30, 67), control1: p(48, 75.059), control2: p(39.941, 67))
                $0.addCurve(to: p(12, 85), control1: p(20.059, 67), control2: p(12, 75.059))
                $0.move(to: p(30, 85))
                $0.move(to: p(21, 85))
                $0.addCurve(to: p(30, 76), control1: p(21, 80.029), control2: p(25.029, 76))
                $0.addCurve(to: p(39, 85), control1: p(34.971, 76), control2: p(39, 80.029))
                $0.addCurve(to: p(30, 94), control1: p(39, 89.971), control2: p(34.971, 94))
                $0.addCurve(to: p(21, 85), control1: p(25.029, 94), control2: p(21, 89.971))
            }
            context.fill(shape7, with: .color(Color(hex: "#800080")), style: FillStyle(eoFill: true))

            // 9. polyline
            let shape8 = shape {
                $0.move(to: p(65, 75))
                $0.addLine(to: p(80, 95))
                $0.addLine(to: p(95, 75))
            }
            context.stroke(shape8, with: .color(Color(hex: "#000000")),
                           style: StrokeStyle(lineWidth: w(6), lineCap: .square, lineJoin: .bevel))

            // 10. line
            let shape9 = shape {
                $0.move(to: p(10, 110))
                $0.addLine(to: p(40, 110))
            }
            context.stroke(shape9, with: .color(Color(hex: "#800000")),
                           style: StrokeStyle(lineWidth: w(6), lineCap: .butt, lineJoin: .miter))

            // 11. rect
            let shape10 = shape {
                $0.move(to: p(10, 105))
                $0.addLine(to: p(24, 105))
                $0.addLine(to: p(24, 113))
                $0.addLine(to: p(10, 113))
                $0.closeSubpath()
            }
            context.fill(shape10, with: .color(Color(hex: "#FF8000").opacity(0.5)))

            // 12. rect
            let shape11 = shape {
                $0.move(to: p(28, 105))
                $0.addLine(to: p(42, 105))
                $0.addLine(to: p(42, 113))
                $0.addLine(to: p(28, 113))
                $0.closeSubpath()
            }
            context.fill(shape11, with: .color(Color(hex: "#112233").opacity(0.267)))

            // 13. rect
            let shape12 = shape {
                $0.move(to: p(46, 105))
                $0.addLine(to: p(60, 105))
                $0.addLine(to: p(60, 113))
                $0.addLine(to: p(46, 113))
                $0.closeSubpath()
            }
            context.fill(shape12, with: .color(Color(hex: "#000000").opacity(0.4)))

            // 14. rect
            let shape13 = shape {
                $0.move(to: p(64, 105))
                $0.addLine(to: p(78, 105))
                $0.addLine(to: p(78, 113))
                $0.addLine(to: p(64, 113))
                $0.closeSubpath()
            }
            context.stroke(shape13, with: .color(Color(hex: "#008000").opacity(0.4)),
                           style: StrokeStyle(lineWidth: w(2), lineCap: .butt, lineJoin: .miter))
        }
        .accessibilityHidden(true)
    }
}

