// Generated by Scripts/svg2swift.swift from shapes.svg - do not edit by hand.
//
// Regenerate with:
//     swift Scripts/svg2swift.swift <path>/shapes.svg ShapesFixtureArt \
//         > Sources/UI/Art/ShapesFixtureArt.swift

import SwiftUI

/// Drawn from `shapes.svg`, authored in a 100 x 100 frame.
///
/// Scales to whatever size it is given: every coordinate goes through `p()`, which maps
/// the design frame onto the view's bounds, so the art has no fixed size of its own.
struct ShapesFixtureArt: View {
    var body: some View {
        Canvas { context, size in
            let rect = CGRect(origin: .zero, size: size)

            /// A design-space point mapped into the view's bounds.
            func p(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
                CGPoint(x: rect.minX + (x - 0) / 100 * rect.width,
                        y: rect.minY + (y - 0) / 100 * rect.height)
            }
            /// Stroke widths key off width alone, matching the rest of `Sources/UI/Art` -
            /// scaling them off the smaller axis thins every line on a non-square frame.
            func w(_ v: CGFloat) -> CGFloat { v / 100 * rect.width }
            func shape(_ build: (inout Path) -> Void) -> Path { var p = Path(); build(&p); return p }

            // 1. rect
            let shape0 = shape {
                $0.move(to: p(19, 78))
                $0.addLine(to: p(81, 78))
                $0.addCurve(to: p(86, 83), control1: p(83.761, 78), control2: p(86, 80.239))
                $0.addLine(to: p(86, 83))
                $0.addCurve(to: p(81, 88), control1: p(86, 85.761), control2: p(83.761, 88))
                $0.addLine(to: p(19, 88))
                $0.addCurve(to: p(14, 83), control1: p(16.239, 88), control2: p(14, 85.761))
                $0.addLine(to: p(14, 83))
                $0.addCurve(to: p(19, 78), control1: p(14, 80.239), control2: p(16.239, 78))
                $0.closeSubpath()
            }
            context.fill(shape0, with: .color(Color(hex: "#C9AE86")))
            context.stroke(shape0, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(4), lineCap: .butt, lineJoin: .miter))

            // 2. path
            let shape1 = shape {
                $0.move(to: p(26, 34))
                $0.addLine(to: p(74, 34))
                $0.addCurve(to: p(50, 76), control1: p(74, 34), control2: p(72, 76))
                $0.addCurve(to: p(26, 34), control1: p(28, 76), control2: p(26, 34))
                $0.closeSubpath()
            }
            context.fill(shape1, with: .color(Color(hex: "#F2EDE2")))
            context.stroke(shape1, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(4), lineCap: .butt, lineJoin: .miter))

            // 3. path
            let shape2 = shape {
                $0.move(to: p(74, 44))
                $0.addCurve(to: p(82.405, 55), control1: p(79.105, 45.908), control2: p(82.405, 50.227))
                $0.addCurve(to: p(74, 66), control1: p(82.405, 59.773), control2: p(79.105, 64.092))
            }
            context.stroke(shape2, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(5), lineCap: .butt, lineJoin: .miter))

            // 4. path
            let shape3 = shape {
                $0.move(to: p(40, 26))
                $0.addQuadCurve(to: p(40, 10), control: p(46, 18))
                $0.addQuadCurve(to: p(40, 10), control: p(34, 2))
            }
            context.stroke(shape3, with: .color(Color(hex: "#B3A8C0").opacity(0.8)),
                           style: StrokeStyle(lineWidth: w(3), lineCap: .butt, lineJoin: .miter))

            // 5. path
            let shape4 = shape {
                $0.move(to: p(52, 24))
                $0.addQuadCurve(to: p(52, 8), control: p(58, 16))
            }
            context.stroke(shape4, with: .color(Color(hex: "#B3A8C0").opacity(0.8)),
                           style: StrokeStyle(lineWidth: w(3), lineCap: .butt, lineJoin: .miter))

            // 6. ellipse
            let shape5 = shape {
                $0.move(to: p(63.941, 58.683))
                $0.addCurve(to: p(54.146, 59.706), control1: p(63.259, 60.784), control2: p(58.873, 61.242))
                $0.addCurve(to: p(46.822, 53.121), control1: p(49.419, 58.17), control2: p(46.14, 55.222))
                $0.addCurve(to: p(56.618, 52.098), control1: p(47.505, 51.02), control2: p(51.891, 50.562))
                $0.addCurve(to: p(63.941, 58.683), control1: p(61.345, 53.634), control2: p(64.624, 56.582))
                $0.closeSubpath()
            }
            context.fill(shape5, with: .color(Color(hex: "#E4453A").opacity(0.55)))

            // 7. circle
            let shape6 = shape {
                $0.move(to: p(24, 18))
                $0.addCurve(to: p(18, 24), control1: p(24, 21.314), control2: p(21.314, 24))
                $0.addCurve(to: p(12, 18), control1: p(14.686, 24), control2: p(12, 21.314))
                $0.addCurve(to: p(18, 12), control1: p(12, 14.686), control2: p(14.686, 12))
                $0.addCurve(to: p(24, 18), control1: p(21.314, 12), control2: p(24, 14.686))
                $0.closeSubpath()
            }
            context.fill(shape6, with: .color(Color(hex: "#F5C242")))
            context.stroke(shape6, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(2), lineCap: .butt, lineJoin: .miter))

            // 8. polygon
            let shape7 = shape {
                $0.move(to: p(82, 10))
                $0.addLine(to: p(90, 26))
                $0.addLine(to: p(74, 26))
                $0.closeSubpath()
            }
            context.fill(shape7, with: .color(Color(hex: "#57A773")))

            // 9. polyline
            let shape8 = shape {
                $0.move(to: p(8, 60))
                $0.addLine(to: p(14, 54))
                $0.addLine(to: p(20, 60))
            }
            context.fill(shape8, with: .color(Color(hex: "#FF0000")))
            context.stroke(shape8, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(2), lineCap: .butt, lineJoin: .miter))

            // 10. line
            let shape9 = shape {
                $0.move(to: p(30, 92))
                $0.addLine(to: p(70, 92))
            }
            context.stroke(shape9, with: .color(Color(hex: "#2B1D14")),
                           style: StrokeStyle(lineWidth: w(2), lineCap: .butt, lineJoin: .miter))
        }
        .accessibilityHidden(true)
    }
}

